apiVersion: apps/v1beta2 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: jupyter-notebook
spec:
  selector:
    matchLabels:
      app: jupyter-notebook
  replicas: 1
  template:
    metadata:
      labels:
        app: jupyter-notebook
    spec:
      containers:
      - name: jupyter-notebook
        image: elopezdelara/miniconda3-spark:latest
        command:
        - jupyter
        - notebook
        args:
        - --ip='*'
        - --port=8888
        - --no-browser
        - --notebook-dir=/opt/notebooks
        - --allow-root
        - --NotebookApp.password='sha1:9fd15fe4a4ce:0b0a713b2cc29caabb2228971971bae993cb86d2'
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
        ports:
        - containerPort: 4040
        - containerPort: 8888
