apiVersion: v1
kind: Service
metadata:
  name: jupyter-notebook
  labels:
    app: jupyter-notebook
spec:
  clusterIP: None
  ports:
  - name: notebook
    port: 8888
  - name: webui
    port: 4040
  selector:
    app: jupyter-notebook
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jupyter-notebook
spec:
  selector:
    matchLabels:
      app: jupyter-notebook
  serviceName: jupyter-notebook
  replicas: 1
  template:
    metadata:
      labels:
        app: jupyter-notebook
    spec:
      containers:
      - name: jupyter-notebook
        image: elopezdelara/miniconda3-spark:latest
        volumeMounts:
        - name: config-volume
          mountPath: /opt/conf
        - name: keys-volume
          mountPath: /opt/keys
        - name: data-volume
          mountPath: /opt/notebooks
        command:
        - jupyter
        - notebook
        args:
        - --ip='*'
        - --port=8888
        - --no-browser
        - --notebook-dir=/opt/notebooks
        - --allow-root
        - --NotebookApp.token=''
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
        ports:
        - containerPort: 4040
        - containerPort: 8888
      volumes:
        - name: config-volume
          configMap:
            name: spark-defaults
        - name: keys-volume
          configMap:
            name: cluster-keys
        - name: data-volume
          gcePersistentDisk:
            pdName: spark-cluster-notebooks
            fsType: ext4