apiVersion: apps/v1beta2 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: spark-worker
spec:
  selector:
    matchLabels:
      app: spark-worker
  replicas: 1
  template:
    metadata:
      labels:
        app: spark-worker
    spec:
      containers:
      - name: spark-worker
        image: elopezdelara/miniconda3-spark:latest
        env:
        - name: SPARK_NO_DAEMONIZE
          value: "1"
        command:
        - start-slave.sh
        args:
        - spark://spark-master:7077
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
        ports:
        - containerPort: 8081
