apiVersion: v1
kind: Service
metadata:
  name: spark-worker
  labels:
    app: spark-worker
spec:
  clusterIP: None
  ports:
  - name: webui
    port: 8081
  selector:
    app: spark-worker
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: spark-worker
spec:
  selector:
    matchLabels:
      app: spark-worker
  serviceName: spark-worker
  replicas: 1
  template:
    metadata:
      labels:
        app: spark-worker
    spec:
      containers:
      - name: spark-worker
        image: elopezdelara/miniconda3-spark:latest
        env:
        - name: SPARK_NO_DAEMONIZE
          value: "1"
        command:
        - start-slave.sh
        args:
        - spark://spark-master:7077
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
        ports:
        - containerPort: 8081
