apiVersion: apps/v1beta2 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: spark-master
spec:
  selector:
    matchLabels:
      app: spark-master
  replicas: 1
  template:
    metadata:
      labels:
        app: spark-master
    spec:
      containers:
      - name: spark-master
        image: elopezdelara/miniconda3-spark:latest
        command:
        - start-master.sh
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
        ports:
        - containerPort: 7077
        - containerPort: 8080
