apiVersion: v1
kind: Service
metadata:
  name: spark-master
  labels:
    app: spark-master
spec:
  clusterIP: None
  ports:
  - name: master
    port: 7077
  - name: webui
    port: 8080
  selector:
    app: spark-master
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: spark-master
spec:
  selector:
    matchLabels:
      app: spark-master
  serviceName: spark-master
  replicas: 1
  template:
    metadata:
      labels:
        app: spark-master
    spec:
      containers:
      - name: spark-master
        image: elopezdelara/miniconda3-spark:latest
        env:
        - name: SPARK_NO_DAEMONIZE
          value: "1"
        command:
        - start-master.sh
        args:
        - --properties-file /opt/conf/spark-defaults.conf
        volumeMounts:
          - name: config-volume
            mountPath: /opt/conf
          - name: data-volume
            mountPath: /opt/notebooks
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
        ports:
        - containerPort: 7077
        - containerPort: 8080
      volumes:
        - name: config-volume
          configMap:
            name: spark-defaults
        - name: data-volume
          gcePersistentDisk:
            pdName: spark-cluster-data
            fsType: ext4
